do not synchronize non-test methods
telekom/testerra-hpqc-connector pull request #3
Opened 2021-05-14 14:26 UTC by radzimir

---
name: Pull Request
about: do not synchronize non-test methods
title: do not synchronize non-test methods
labels: enhancement
assignees: ''
---

# Description

This avids warnings for non-test methods, like for example "setUpClass": 

QualityCenterSyncUtils.getTestSetTestForAnnotation:265 - No method setUpClass found in Testset Root\...\int\Sprint 65: Sprint64 Inkrement TC_R2.1.1\Chrome ANT1: STB; Risklevel1. Could not synchronize with QC!

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings

2021-05-17 07:37 UTC, mbeuthan approved these changes

2021-05-17 11:57 UTC, mreiche commented on qc11-connector/src/main/java/eu/tsystems/mms/tic/testframework/qcconnector/synchronize/QualityCenterTestResultSynchronizer.java
> +                if( ! method.isAnnotationPresent(Test.class) ) {
Please use `testResult.getMethod().isTest()`

2021-05-17 11:58 UTC, mreiche requested changes
Please see comment on detecting test method.

2021-05-25 11:17 UTC, mreiche approved these changes

2021-05-25 11:17 UTC, merged